server:
  port: 8087
spring:
  application:
    name: demo

check-common:
  audit-enable: true
  log-execution-time: false
  retry:
    enabled: true
    default-max-attempts: 3
    default-delay-ms: 500


logging:
  level:
    org.springframework.aop: INFO
